name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2      

    - name: stylelinter
      uses: actions-hub/stylelint@v1.1.2
      env:
        INDENT_SPACES: 4
        PATTERN: "styles/*.css"
